version: "3.3"

services:
  node:
    container_name: clinic_backend
    restart: always
    image: node:16.10.0
    ports: 
    - 3003:3002
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks:
      - clinic_network

    command: bash -c "npm install && npm run start:prod"

networks:
  clinic_network:
    driver: bridge
